auto_sync = true
sync_frequency = "30s"

search_mode = "daemon-fuzzy"
filter_mode = "global"
search_mode_shell_up_key_binding = "prefix"
filter_mode_shell_up_key_binding = "global"
enter_accept = true

[sync]
records = true

[daemon]
enabled = true
autostart = true
sync_frequency = 30
