fish: shell
vimrc: vim
viminfo: vim
lock: env
toml: yml
m3u: video
dat: db
pid: id
7z: zip
tgz: zip

h: c
cc: c
swig: c

build: info
metadata: info
owners: info
blueprint: env
proto: conf
pbtxt: txt
schema: db
sql: db
sqlm: db
sqlt: test
