#!/usr/bin/env zsh

append_content_if_absent () {
  local file="$1" text="$2" appending=${3:-$2}
  if ! grep "$text" "$file" &>/dev/null; then
    [ -f "$appending" ] && cat "$appending" >> "$file" || echo "$appending" >> "$file"
  fi
}

RAVY="${0:A:h}"

echo "dotfiles"
append_content_if_absent ~/.zshrc "[ -f $RAVY/zshrc ] && source $RAVY/zshrc"
append_content_if_absent ~/.zshenv "[ -f $RAVY/zshenv ] && source $RAVY/zshenv"
append_content_if_absent ~/.tmux.conf "source -q $RAVY/tmux.conf"
append_content_if_absent ~/.gitconfig "path=$RAVY/gitconfig" "[include]\npath=$RAVY/gitconfig\npath=$RAVY/custom/gitconfig"
append_content_if_absent ~/.ignore "RAVY_TMP" "$RAVY/ignore"

echo "zplug"
[ -d ~/.zplug ] || git clone https://github.com/zplug/zplug ~/.zplug

echo "vim"
append_content_if_absent ~/.vimrc "if filereadable(\"$RAVY/vimrc\") | source $RAVY/vimrc | endif"
mkdir -p ~/.vim ~/.vim/bundle ~/.vim/tmp ~/.vim/autoload ~/.config

[ -d ~/.config/nvim ] || ln -s -f ~/.vim ~/.config/nvim
ln -s -f ~/.vimrc ~/.config/nvim/init.vim

[ -e ~/.vim/autoload/plug.vim ] || curl -sfLo ~/.vim/autoload/plug.vim \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "tmux"
mkdir -p ~/.tmux ~/.tmux/plugins
[ -d ~/.tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

echo "custom configs"
mkdir -p "$RAVY/custom" "$RAVY/custom/bin" "$RAVY/custom/zsh-functions"
touch "$RAVY/custom/zshrc" "$RAVY/custom/vimrc" "$RAVY/custom/gitconfig"

command -v "$RAVY/custom/install" >/dev/null && "$RAVY/custom/install" || true
