#!/usr/bin/env zsh

RAVY="${0:A:h}"

echo 'Linking dotfiles'
if ! grep "RAVY_TMP" ~/.ignore &>/dev/null; then
  cat $RAVY/ignore >> ~/.ignore
fi

if ! grep "source $RAVY/zshrc" ~/.zshrc &>/dev/null; then
  echo "source $RAVY/zshrc" >> ~/.zshrc
fi
if ! grep "source $RAVY/zshenv" ~/.zshenv &>/dev/null; then
  echo "source $RAVY/zshenv" >> ~/.zshenv
fi
if ! grep "path=$RAVY/gitconfig" ~/.gitconfig &>/dev/null; then
  echo "[include]\npath=$RAVY/gitconfig\npath=$RAVY/custom/gitconfig" \
    >> ~/.gitconfig
fi
if ! grep "source $RAVY/tmux.conf" ~/.tmux.conf &>/dev/null; then
  echo "source $RAVY/tmux.conf" >> ~/.tmux.conf
fi

echo 'Configuring Vim/NeoVim'
if ! grep "source $RAVY/vimrc" ~/.vimrc &>/dev/null; then
  echo "source $RAVY/vimrc" >> ~/.vimrc
fi
mkdir -p ~/.vim ~/.vim/bundle ~/.vim/tmp ~/.vim/autoload ~/.config
if [[ ! -d ~/.config/nvim ]]; then
  ln -s -f ~/.vim ~/.config/nvim
fi
ln -s -f ~/.vimrc ~/.config/nvim/init.vim

echo 'Configuring mpv'
mkdir -p ~/.config ~/.config/mpv
ln -s -f $RAVY/mpv.conf ~/.config/mpv/mpv.conf

if [[ ! -e ~/.vim/autoload/plug.vim || -n $RAVY_UPDATE ]]; then
  curl -sfLo ~/.vim/autoload/plug.vim \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo 'Touching custom files'
mkdir -p $RAVY/custom $RAVY/custom/bin $RAVY/custom/zsh-functions
touch $RAVY/custom/zshrc
touch $RAVY/custom/vimrc
touch $RAVY/custom/gitconfig

echo 'Installing Zplug'
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
elif [[ -n $RAVY_UPDATE ]]; then
  git -C ~/.zplug pull --rebase
fi

echo 'Installing custom settings'
if command -v $RAVY/custom/install >/dev/null; then
  $RAVY/custom/install
fi

if [[ -d ~/Library/Rime ]]; then
  echo 'Installing rime custom settings'
  cp $RAVY/rime/* ~/Library/Rime
fi
