#!/usr/bin/env zsh

append_content_if_absent () {
  local file="$1" text="$2" appending=${3:-$2}
  if ! grep "$text" "$file" &>/dev/null; then
    [ -f "$appending" ] && cat "$appending" >> "$file" || echo "$appending" >> "$file"
  fi
}

RAVY="${0:A:h}"

echo "dotfiles"
append_content_if_absent ~/.zshrc "[ -f $RAVY/zshrc ] && source $RAVY/zshrc"
append_content_if_absent ~/.zshenv "[ -f $RAVY/zshenv ] && source $RAVY/zshenv"
append_content_if_absent ~/.gitconfig "path=$RAVY/gitconfig" "[include]\npath=$RAVY/gitconfig\npath=$RAVY/custom/gitconfig"
append_content_if_absent ~/.ignore "RAVY_TMP" "$RAVY/ignore"

echo "zplug"
[ -d ~/.zplug ] || git clone https://github.com/zplug/zplug ~/.zplug

echo "vim/neovim"
mkdir -p ~/.vim ~/.vim/bundle ~/.vim/tmp ~/.vim/autoload ~/.config
[ -d ~/.config/nvim ] || ln -s -f ~/.vim ~/.config/nvim

append_content_if_absent ~/.vimrc "if filereadable(\"$RAVY/vimrc\") | source $RAVY/vimrc | endif"
append_content_if_absent ~/.config/nvim/init.vim "if filereadable(\"$RAVY/vimrc\") | source $RAVY/vimrc | endif"

[ -e ~/.vim/autoload/plug.vim ] || curl -sfLo ~/.vim/autoload/plug.vim \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "vim plugins"
vim '+PlugUpdate' '+qall'

echo "tmux"
ln -s -f $RAVY/tmux.conf ~/.tmux.conf
ln -s -f $RAVY/tmux.conf.local ~/.tmux.conf.local

echo "custom configs"
mkdir -p "$RAVY/custom" "$RAVY/custom/bin" "$RAVY/custom/zsh-functions"
touch "$RAVY/custom/zshrc" "$RAVY/custom/vimrc" "$RAVY/custom/gitconfig"

command -v "$RAVY/custom/install" >/dev/null && "$RAVY/custom/install" || true
