[tools]
python = "3.14"
uv = "latest"
jq = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
zoxide = "latest"
starship = "latest"
ripgrep = "latest"
process-compose = "latest"
duckdb = "latest"
zellij = "0.44.1"


[settings]
python.uv_venv_auto = false
