[tools]
chezmoi = "latest"
age = "latest"
"aqua:neovim" = "latest"
python = "3.14.5"
uv = "latest"
jq = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
zoxide = "latest"
starship = "latest"
carapace = "latest"
usage = "latest"
ripgrep = "latest"
process-compose = "latest"
duckdb = "latest"
zellij = "latest"
herdr = "latest"
rclone = "latest"
atuin = "latest"


[settings]
python.uv_venv_auto = false
minimum_release_age = "0d"
