# Hermes Agent fish completion
# Add to your config:
#   hermes completion fish | source

# Helper: list available profiles
function __hermes_profiles
    echo default
    if test -d $HOME/.hermes/profiles
        for d in $HOME/.hermes/profiles/*/
            basename $d
        end
    end
end

# Disable file completion by default
complete -c hermes -f

# Complete profile names after -p / --profile
complete -c hermes -f -s p -l profile -d 'Profile name' -xa '(__hermes_profiles)'

# Top-level subcommands
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a acp -d 'Run Hermes Agent as an ACP (Agent Client Protocol) server'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a approvals -d 'Approval-prompt tools (mine history into allowlist proposals'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a auth -d 'Manage pooled provider credentials'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a backup -d 'Back up Hermes home directory to a zip file'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a bundles -d 'Create, list, and manage skill bundles (aliases for multiple'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a chat -d 'Interactive chat with the agent'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a checkpoints -d 'Inspect / prune / clear ~/.hermes/checkpoints/'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a claw -d 'OpenClaw migration tools'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a completion -d 'Print shell completion script (bash, zsh, or fish)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a computer-use -d 'Manage the Computer Use (cua-driver) backend (macOS/Windows/'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a config -d 'View and edit configuration'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a console -d 'Open the safe Hermes command console'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a cron -d 'Cron job management'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a curator -d 'Background skill maintenance (curator) — status, run, pause,'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a dashboard -d 'Start the web UI dashboard'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a debug -d 'Debug tools — upload logs and system info for support'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a desktop -d 'Build and launch the native desktop app'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a doctor -d 'Check configuration and dependencies'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a dump -d 'Dump setup summary for support/debugging'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a egress -d 'Manage the iron-proxy egress credential-injection firewall'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a fallback -d 'Manage fallback providers (tried when the primary model fail'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a gateway -d 'Messaging gateway management'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a hooks -d 'Inspect and manage shell-script hooks'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a import -d 'Restore a Hermes backup from a zip file'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a insights -d 'Show usage insights and analytics'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a journey -d 'Timeline of learned skills + memories over time'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a kanban -d 'Multi-profile collaboration board (tasks, links, comments)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a logout -d 'Clear authentication for an inference provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a logs -d 'View and filter Hermes log files'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a lsp -d 'Language Server Protocol management'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a mcp -d 'Manage MCP servers and run Hermes as an MCP server'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a memory -d 'Configure external memory provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a migrate -d 'Migrate configuration for retired models or deprecated setti'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a moa -d 'Configure Mixture of Agents provider/model slots'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a model -d 'Select default model and provider'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a pairing -d 'Manage DM pairing codes for user authorization'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a pets -d 'Browse, install, and select petdex animated pets'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a plugins -d 'Manage plugins — install, update, remove, list'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a portal -d 'Set up Nous Portal (login, model pick, Tool Gateway); see al'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a profile -d 'Manage profiles — multiple isolated Hermes instances'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a project -d 'Manage projects (named, multi-folder workspaces)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a prompt-size -d 'Show a byte breakdown of the system prompt + tool schemas'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a proxy -d 'Local OpenAI-compatible proxy to OAuth providers'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a secrets -d 'Manage external secret sources (Bitwarden, 1Password)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a security -d 'Supply-chain audit (OSV.dev) for venv, plugins, and MCP serv'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a send -d 'Send a message to a configured platform (scripts, cron jobs,'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a serve -d 'Start the Hermes backend server (headless; powers the deskto'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a sessions -d 'Manage session history (list, rename, export, prune, delete)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a setup -d 'Interactive setup wizard'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a skills -d 'Search, install, configure, and manage skills'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a skin -d 'List, switch, and tweak skins'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a slack -d 'Slack integration helpers (manifest generation, etc.)'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a status -d 'Show status of all components'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a tools -d 'Configure which tools are enabled per platform'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a uninstall -d 'Uninstall Hermes Agent'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a update -d 'Update Hermes Agent to the latest version'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a version -d 'Show version information'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a webhook -d 'Manage dynamic webhook subscriptions'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a whatsapp -d 'Set up WhatsApp integration'
complete -c hermes -f -n 'not __fish_seen_subcommand_from acp approvals auth backup bundles chat checkpoints claw completion computer-use config console cron curator dashboard debug desktop doctor dump egress fallback gateway hooks import insights journey kanban logout logs lsp mcp memory migrate moa model pairing pets plugins portal profile project prompt-size proxy secrets security send serve sessions setup skills skin slack status tools uninstall update version webhook whatsapp whatsapp-cloud' -a whatsapp-cloud -d 'Set up WhatsApp Business Cloud API integration'

# Subcommand completions
# approvals
complete -c hermes -f -n '__fish_seen_subcommand_from approvals' -a suggest -d 'Propose command_allowlist entries from past approvals'
# auth
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a add -d 'Add a pooled credential'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a list -d 'List pooled credentials'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a logout -d 'Log out a provider and clear stored auth state'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a remove -d 'Remove a pooled credential by index, id, or label'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a reset -d 'Clear exhaustion status for all credentials for a provider'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a spotify -d 'Authenticate Hermes with Spotify via PKCE'
complete -c hermes -f -n '__fish_seen_subcommand_from auth' -a status -d 'Show auth status for a provider'
# bundles
complete -c hermes -f -n '__fish_seen_subcommand_from bundles' -a create -d 'Create a new skill bundle'
complete -c hermes -f -n '__fish_seen_subcommand_from bundles' -a delete -d 'Delete a skill bundle'
complete -c hermes -f -n '__fish_seen_subcommand_from bundles' -a list -d 'List installed skill bundles'
complete -c hermes -f -n '__fish_seen_subcommand_from bundles' -a reload -d 'Re-scan the bundles directory and report changes'
complete -c hermes -f -n '__fish_seen_subcommand_from bundles' -a show -d 'Show one bundles contents'
# checkpoints
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a clear -d 'Delete the entire checkpoint base (all /rollback history)'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a clear-legacy -d 'Delete only the legacy-<ts>/ archives from v1 migration'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a list -d 'Alias for status'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a prune -d 'Delete orphan/stale checkpoints and GC the store'
complete -c hermes -f -n '__fish_seen_subcommand_from checkpoints' -a status -d 'Show total size, project count, and per-project breakdown'
# claw
complete -c hermes -f -n '__fish_seen_subcommand_from claw' -a cleanup -d 'Archive leftover OpenClaw directories after migration'
complete -c hermes -f -n '__fish_seen_subcommand_from claw' -a migrate -d 'Migrate from OpenClaw to Hermes'
# computer-use
complete -c hermes -f -n '__fish_seen_subcommand_from computer-use' -a doctor -d 'Run cua-driver `health_report` and surface the check matrix'
complete -c hermes -f -n '__fish_seen_subcommand_from computer-use' -a install -d 'Install or repair the cua-driver binary (macOS/Windows/Linux'
complete -c hermes -f -n '__fish_seen_subcommand_from computer-use' -a permissions -d 'Check or grant macOS Accessibility + Screen Recording (macOS'
complete -c hermes -f -n '__fish_seen_subcommand_from computer-use' -a status -d 'Print whether cua-driver is installed and on PATH'
# config
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a check -d 'Check for missing/outdated config'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a edit -d 'Open config file in editor'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a env-path -d 'Print .env file path'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a get -d 'Print a resolved configuration value'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a migrate -d 'Update config with new options'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a path -d 'Print config file path'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a set -d 'Set a configuration value'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a show -d 'Show current configuration'
complete -c hermes -f -n '__fish_seen_subcommand_from config' -a unset -d 'Remove a configuration value'
# cron
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a create -d 'Create a scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a edit -d 'Edit an existing scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a list -d 'List scheduled jobs'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a pause -d 'Pause a scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a remove -d 'Remove a scheduled job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a resume -d 'Resume a paused job'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a run -d 'Run a job on the next scheduler tick'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a runs -d 'Show durable execution attempts'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a status -d 'Check if cron scheduler is running'
complete -c hermes -f -n '__fish_seen_subcommand_from cron' -a tick -d 'Run due jobs once and exit'
# curator
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a adopt -d 'Hand unmanaged skills to the curator (provenance is a user d'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a archive -d 'Manually archive a skill (move to .archive/, excluded from p'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a backup -d 'Take a manual tar.gz snapshot of ~/.hermes/skills/ (curator '
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a list-archived -d 'List archived skills'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a list-unmanaged -d 'List curation-eligible skills with no provenance marker'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a pause -d 'Pause the curator until resumed'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a pin -d 'Pin a skill so the curator never auto-transitions it'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a prune -d 'Bulk-archive curator-managed skills idle for >= N days (defa'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a restore -d 'Restore an archived skill'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a resume -d 'Resume a paused curator'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a rollback -d 'Restore ~/.hermes/skills/ from a curator snapshot (defaults '
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a run -d 'Trigger a curator review now'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a status -d 'Show curator status and skill stats'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a unpin -d 'Unpin a skill'
complete -c hermes -f -n '__fish_seen_subcommand_from curator' -a usage -d 'Show usage telemetry for ALL skills (built-in, hub, agent) w'
# dashboard
complete -c hermes -f -n '__fish_seen_subcommand_from dashboard' -a register -d 'Register a self-hosted dashboard with Nous Portal (writes th'
# debug
complete -c hermes -f -n '__fish_seen_subcommand_from debug' -a delete -d 'Delete a paste uploaded by hermes debug share'
complete -c hermes -f -n '__fish_seen_subcommand_from debug' -a share -d 'Upload debug report to a paste service and print a shareable'
# egress
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a config -d 'Print the generated proxy.yaml path'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a disable -d 'Turn off the proxy integration'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a install -d 'Download iron-proxy binary (v0.39.0)'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a reload -d 'Hot-reload the running daemons ruleset from proxy.yaml (mana'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a restart -d 'Restart the managed iron-proxy (stop if running, then start)'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a setup -d 'Interactive wizard: install + CA + mint tokens + write confi'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a start -d 'Start the managed iron-proxy'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a status -d 'Show proxy state and mappings'
complete -c hermes -f -n '__fish_seen_subcommand_from egress' -a stop -d 'Stop the managed iron-proxy'
# fallback
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a add -d 'Pick a provider + model (same picker as `hermes model`) and '
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a clear -d 'Remove all fallback entries'
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a list -d 'Show the current fallback chain (default when no subcommand)'
complete -c hermes -f -n '__fish_seen_subcommand_from fallback' -a remove -d 'Pick an entry to delete from the chain'
# gateway
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a enroll -d 'Enroll this gateway with a relay connector (writes relay aut'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a install -d 'Install gateway as a systemd/launchd background service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a list -d 'List all profiles and their gateway status'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a migrate-legacy -d 'Remove legacy hermes.service units from pre-rename installs'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a restart -d 'Restart gateway service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a run -d 'Run gateway in foreground (recommended for WSL, Docker, Term'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a setup -d 'Configure messaging platforms'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a start -d 'Start the installed systemd/launchd background service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a status -d 'Show gateway status'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a stop -d 'Stop gateway service'
complete -c hermes -f -n '__fish_seen_subcommand_from gateway' -a uninstall -d 'Uninstall gateway service'
# hooks
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a doctor -d 'Check each configured hook: exec bit, allowlist, mtime drift'
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a list -d 'List configured hooks with matcher, timeout, and consent sta'
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a revoke -d 'Remove a commands allowlist entries (takes effect on next re'
complete -c hermes -f -n '__fish_seen_subcommand_from hooks' -a test -d 'Fire every hook matching <event> against a synthetic payload'
# journey
complete -c hermes -f -n '__fish_seen_subcommand_from journey' -a delete -d 'Delete a learned skill (archived) or memory by node id.'
complete -c hermes -f -n '__fish_seen_subcommand_from journey' -a edit -d 'Edit a learned skill or memory by node id in $EDITOR.'
complete -c hermes -f -n '__fish_seen_subcommand_from journey' -a list -d 'List node ids (for delete/edit).'
# kanban
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a archive -d 'Archive one or more tasks'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a assign -d 'Assign or reassign a task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a assignees -d 'List known profiles + per-profile task counts (union of ~/.h'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a attach -d 'Attach a local file to a task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a attach-rm -d 'Delete an attachment by id'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a attachments -d 'List a tasks attachments'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a block -d 'Mark one or more tasks blocked'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a boards -d 'Manage kanban boards (one board per project / workstream)'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a claim -d 'Atomically claim a ready task (prints resolved workspace pat'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a comment -d 'Append a comment'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a complete -d 'Mark one or more tasks done'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a context -d 'Print the full context a worker sees for a task (title + bod'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a create -d 'Create a new task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a daemon -d 'DEPRECATED — dispatcher now runs in the gateway. Use `hermes'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a decompose -d 'Decompose a triage-column task into a graph of child tasks r'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a diagnostics -d 'List active diagnostics on the current board'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a dispatch -d 'One dispatcher pass: reclaim stale, promote ready, spawn wor'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a edit -d 'Edit recovery fields on an already-completed task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a gc -d 'Garbage-collect archived-task workspaces, old events, and ol'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a heartbeat -d 'Emit a heartbeat event for a running task (worker liveness s'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a init -d 'Create kanban.db if missing (idempotent)'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a link -d 'Add a parent->child dependency'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a list -d 'List tasks'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a log -d 'Print the worker log for a task (from <kanban-root>/kanban/l'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a notify-list -d 'List notification subscriptions (optionally for a single tas'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a notify-subscribe -d 'Subscribe a gateway source to a tasks terminal events (used '
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a notify-unsubscribe -d 'Remove a gateway subscription from a task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a promote -d 'Manually move one or more todo/blocked tasks to ready (recov'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a reassign -d 'Reassign a task to a different profile, optionally reclaimin'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a reclaim -d 'Release an active worker claim on a running task'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a repair -d 'Check kanban.db integrity and auto-repair index-only corrupt'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a runs -d 'Show attempt history for a task (one row per run: profile, o'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a schedule -d 'Park one or more tasks in Scheduled (waiting on time, not hu'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a set-model -d 'Set or clear a tasks model/provider override (takes effect o'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a show -d 'Show a task with comments + events'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a specify -d 'Flesh out a triage-column task into a concrete spec (title +'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a stats -d 'Per-status + per-assignee counts + oldest-ready age'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a swarm -d 'Create a Kanban Swarm v1 graph (parallel workers → verifier '
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a tail -d 'Follow a tasks event stream'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a unblock -d 'Return blocked/scheduled tasks to ready, or todo while paren'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a unlink -d 'Remove a parent->child dependency'
complete -c hermes -f -n '__fish_seen_subcommand_from kanban' -a watch -d 'Live-stream task_events to the terminal (Ctrl+C to exit)'
# lsp
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a install -d 'Install a server binary'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a install-all -d 'Install every server with a known auto-install recipe'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a list -d 'List supported language servers'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a restart -d 'Tear down running LSP clients (next edit re-spawns)'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a status -d 'Show LSP service status'
complete -c hermes -f -n '__fish_seen_subcommand_from lsp' -a which -d 'Print binary path for a server'
# mcp
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a add -d 'Add an MCP server (discovery-first install)'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a catalog -d 'List Nous-approved MCPs available for one-click install'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a configure -d 'Toggle tool selection'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a install -d 'Install a catalog MCP by name (e.g. `hermes mcp install n8n`'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a list -d 'List configured MCP servers'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a login -d 'Force re-authentication for an OAuth-based MCP server'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a picker -d 'Interactive catalog picker (also the default for `hermes mcp'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a reauth -d 'Re-authenticate one OAuth MCP server, or all of them (--all)'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a remove -d 'Remove an MCP server'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a serve -d 'Run Hermes as an MCP server (expose conversations to other a'
complete -c hermes -f -n '__fish_seen_subcommand_from mcp' -a test -d 'Test MCP server connection'
# memory
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a off -d 'Disable external provider (built-in only)'
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a reset -d 'Erase all built-in memory (MEMORY.md and USER.md)'
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a setup -d 'Interactive provider selection and configuration'
complete -c hermes -f -n '__fish_seen_subcommand_from memory' -a status -d 'Show current memory provider config'
# migrate
complete -c hermes -f -n '__fish_seen_subcommand_from migrate' -a xai -d 'Migrate xAI models scheduled for retirement on May 15, 2026'
# moa
complete -c hermes -f -n '__fish_seen_subcommand_from moa' -a configure -d 'Interactively pick MoA models'
complete -c hermes -f -n '__fish_seen_subcommand_from moa' -a delete -d 'Delete a MoA preset'
complete -c hermes -f -n '__fish_seen_subcommand_from moa' -a list -d 'Show current MoA model slots'
# pairing
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a approve -d 'Approve a pairing code'
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a clear-pending -d 'Clear all pending codes'
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a list -d 'Show pending + approved users'
complete -c hermes -f -n '__fish_seen_subcommand_from pairing' -a revoke -d 'Revoke user access'
# pets
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a doctor -d 'Check pet setup + terminal graphics support'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a install -d 'Install a pet from the gallery'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a list -d 'Browse the petdex gallery'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a off -d 'Disable the pet display'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a remove -d 'Delete an installed pet'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a scale -d 'Resize the pet everywhere (display.pet.scale)'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a select -d 'Set the active pet (writes display.pet.*)'
complete -c hermes -f -n '__fish_seen_subcommand_from pets' -a show -d 'Animate the active pet in the terminal'
# plugins
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a disable -d 'Disable a plugin without removing it'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a enable -d 'Enable a disabled plugin'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a install -d 'Install a plugin from a Git URL or owner/repo'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a list -d 'List installed plugins'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a remove -d 'Remove an installed plugin'
complete -c hermes -f -n '__fish_seen_subcommand_from plugins' -a update -d 'Pull latest changes for an installed plugin'
# portal
complete -c hermes -f -n '__fish_seen_subcommand_from portal' -a info -d 'Show Portal auth + Tool Gateway routing summary'
complete -c hermes -f -n '__fish_seen_subcommand_from portal' -a login -d 'Log in to Nous Portal + set it up (default; one-shot onboard'
complete -c hermes -f -n '__fish_seen_subcommand_from portal' -a open -d 'Open the Portal subscription page in your default browser'
complete -c hermes -f -n '__fish_seen_subcommand_from portal' -a tools -d 'List Tool Gateway tools and which are routed via Nous'
# profile
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a alias -d 'Manage wrapper scripts'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a create -d 'Create a new profile'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a delete -d 'Delete a profile'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a describe -d 'Read or set a profiles description (used by the kanban orche'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a export -d 'Export a profile to archive'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a import -d 'Import a profile from archive'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a info -d 'Show a profiles distribution manifest (version, requirements'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a install -d 'Install a profile distribution from a git URL or local direc'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a list -d 'List all profiles'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a rename -d 'Rename a profile'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a show -d 'Show profile details'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a update -d 'Re-pull a distribution and apply updates (user data preserve'
complete -c hermes -f -n '__fish_seen_subcommand_from profile' -a use -d 'Set sticky default profile'
complete -c hermes -f -n '__fish_seen_subcommand_from alias; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from export; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from rename; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from show; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
complete -c hermes -f -n '__fish_seen_subcommand_from use; and __fish_seen_subcommand_from profile' -a '(__hermes_profiles)' -d 'Profile name'
# project
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a add-folder -d 'Add a folder to a project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a archive -d 'Archive a project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a bind-board -d 'Bind a kanban board to a project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a create -d 'Create a new project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a list -d 'List projects'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a remove-folder -d 'Remove a folder from a project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a rename -d 'Rename a project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a restore -d 'Restore an archived project'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a set-primary -d 'Set the primary folder'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a show -d 'Show a projects details'
complete -c hermes -f -n '__fish_seen_subcommand_from project' -a use -d 'Set the active project'
# proxy
complete -c hermes -f -n '__fish_seen_subcommand_from proxy' -a providers -d 'List available proxy upstream providers'
complete -c hermes -f -n '__fish_seen_subcommand_from proxy' -a start -d 'Run the proxy in the foreground'
complete -c hermes -f -n '__fish_seen_subcommand_from proxy' -a status -d 'Show which proxy upstreams are ready'
# secrets
complete -c hermes -f -n '__fish_seen_subcommand_from secrets' -a bitwarden -d 'Bitwarden Secrets Manager integration'
complete -c hermes -f -n '__fish_seen_subcommand_from secrets' -a onepassword -d '1Password (op:// references) integration'
# security
complete -c hermes -f -n '__fish_seen_subcommand_from security' -a audit -d 'Run a one-shot supply-chain audit'
# sessions
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a archive -d 'Bulk-archive (soft-hide) sessions matching filters — no dele'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a browse -d 'Interactive session picker — browse, search, and resume sess'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a delete -d 'Delete a specific session'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a export -d 'Export sessions to JSONL, Markdown, or QMD'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a list -d 'List recent sessions'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a optimize -d 'Reclaim disk space: merge FTS5 segments + VACUUM (no data ch'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a optimize-storage -d 'Migrate the search index to the compact v23 layout (reclaims'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a prune -d 'Delete old sessions (filterable by time window, source, titl'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a recover -d 'Rebuild canonical session data into a separate clean databas'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a rename -d 'Set or change a sessions title'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a repair -d 'Repair a malformed state.db schema so hidden sessions reappe'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a retitle-skills -d 'Re-title sessions whose auto-title came from a /skills own t'
complete -c hermes -f -n '__fish_seen_subcommand_from sessions' -a stats -d 'Show session store statistics'
# skills
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a audit -d 'Re-scan installed hub skills'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a browse -d 'Browse all available skills (paginated)'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a check -d 'Check installed hub skills for updates'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a config -d 'Interactive skill configuration — enable/disable individual '
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a diff -d 'Show how your copy of a bundled skill differs from the stock'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a inspect -d 'Preview a skill without installing'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a install -d 'Install a skill'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a list -d 'List installed skills'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a list-modified -d 'List bundled skills youve edited (which `hermes update` keep'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a opt-in -d 'Re-enable bundled-skill seeding (undo opt-out)'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a opt-out -d 'Stop bundled skills from being seeded into this profile'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a publish -d 'Publish a skill to a registry'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a repair-official -d 'Backfill or restore official optional skills from repo sourc'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a reset -d 'Reset a bundled skill — clears user-modified tracking so upd'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a search -d 'Search skill registries'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a snapshot -d 'Export/import skill configurations'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a tap -d 'Manage skill sources'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a uninstall -d 'Remove a hub-installed skill'
complete -c hermes -f -n '__fish_seen_subcommand_from skills' -a update -d 'Update installed hub skills'
# skin
complete -c hermes -f -n '__fish_seen_subcommand_from skin' -a list -d 'List available skins'
complete -c hermes -f -n '__fish_seen_subcommand_from skin' -a set -d 'Set one color of the active skin (e.g. `skin set ui_tool #00'
complete -c hermes -f -n '__fish_seen_subcommand_from skin' -a use -d 'Switch the active skin'
# slack
complete -c hermes -f -n '__fish_seen_subcommand_from slack' -a manifest -d 'Print or write a Slack app manifest with every gateway comma'
# tools
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a disable -d 'Disable toolsets or MCP tools'
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a enable -d 'Enable toolsets or MCP tools'
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a list -d 'Show all tools and their enabled/disabled status'
complete -c hermes -f -n '__fish_seen_subcommand_from tools' -a post-setup -d 'Run a providers post-setup install hook (npm/pip/binary)'
# webhook
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a list -d 'List all dynamic subscriptions'
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a remove -d 'Remove a subscription'
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a subscribe -d 'Create a webhook subscription'
complete -c hermes -f -n '__fish_seen_subcommand_from webhook' -a test -d 'Send a test POST to a webhook route'

