#!/usr/bin/env bash

set -euo pipefail

os_name="${RAVY_NUSHELL_OS:-$(uname -s)}"

if [ "$os_name" != "Darwin" ]; then
  exit 0
fi

canonical_dir="$HOME/.config/nushell"
native_dir="$HOME/Library/Application Support/nushell"
canonical_history="$canonical_dir/history.txt"
native_history="$native_dir/history.txt"

mkdir -p "$canonical_dir" "$native_dir"

write_shim() {
  local target=$1
  local mode=$2
  local source_name=$3
  local tmp_file

  tmp_file=$(mktemp "$native_dir/.ravy-nushell-shim.XXXXXX")
  cat > "$tmp_file" <<EOF
# Generated by ravy/scripts/nushell-harness.sh
const ravy_native = (\$nu.config-path | path dirname)
const ravy_home = (\$ravy_native | path dirname --num-levels 3)
const ravy_canonical = (\$ravy_home | path join ".config" "nushell")
$mode (\$ravy_canonical | path join "$source_name")
EOF
  mv -f "$tmp_file" "$target"
}

append_file() {
  local target=$1
  local source=$2
  local trailing_byte

  [ -s "$source" ] || return 0
  [ -e "$target" ] || : > "$target"

  if [ -s "$target" ]; then
    trailing_byte=$(tail -c 1 "$target" | od -An -tx1 | tr -d ' \n')
    if [ "$trailing_byte" != "0a" ]; then
      printf '\n' >> "$target"
    fi
  fi

  cat "$source" >> "$target"
}

link_history() {
  if [ -L "$native_history" ]; then
    local current_target

    current_target=$(readlink "$native_history")
    if [ "$current_target" = "$canonical_history" ]; then
      [ -e "$canonical_history" ] || : > "$canonical_history"
      return 0
    fi

    if [ -e "$native_history" ]; then
      append_file "$canonical_history" "$native_history"
    else
      [ -e "$canonical_history" ] || : > "$canonical_history"
    fi

    ln -sfn "$canonical_history" "$native_history"
    return 0
  fi

  if [ -f "$native_history" ]; then
    if [ -e "$canonical_history" ]; then
      append_file "$canonical_history" "$native_history"
    else
      mv -f "$native_history" "$canonical_history"
    fi

    ln -sfn "$canonical_history" "$native_history"
    return 0
  fi

  if [ -e "$native_history" ]; then
    printf 'warning: leaving unexpected Nushell history path untouched: %s\n' "$native_history" >&2
    return 0
  fi

  [ -e "$canonical_history" ] || : > "$canonical_history"
  ln -sfn "$canonical_history" "$native_history"
}

write_shim "$native_dir/env.nu" "source-env" "env.nu"
write_shim "$native_dir/config.nu" "source" "config.nu"
write_shim "$native_dir/login.nu" "source" "login.nu"
link_history
