brew "cloudflare-speed-cli"
brew "fish"
brew "imagemagick"
brew "universal-ctags"
brew "pv"

if OS.mac?
  tap "laishulu/homebrew"
  brew "laishulu/homebrew/macism"

  brew "socat"
  brew "lftp"

  cask "font-inconsolata-nerd-font"
end
